# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb9607b2c7bcae72a7f2e166fba0013d63e7c34f51903d7d2e4b6f966c9d64d5b890619529dc7c601bdaa39dd464a5d9f865dc2c50a0c8cef804f36cb4d4843

test:
  secret_key_base: 2fdfe0c3a5740ec2376bb69bf9271d2691332720a09e26c57603bdb04160bc61c9353e050b3749ec20722f1fe1d57d200d224bf0dae9373dd095a671fb942e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
